### ISSUE TITLE
Cannot edit my profile

### ISSUE THREAD

**Issue by vanangamudi** [adamshamsudeen/DataTagger#2]
I cloned the repo and ran migrations. I am able register and login. But when I try to edit my profile, I cannot edit languages and the mother tongue list box is empty

**Comment by adamshamsudeen** [comment]
The table for language is empty that is causing this issue. Can you pull the latest version?  I have added the sqlite file.

**Comment by vanangamudi** [comment]
Closing this, since not an issue

**Comment by vanangamudi** [comment]
Closing this, since not an issue
